language: java
sudo: true
jdk:
  - openjdk8
install: true
services:
  - docker
git:
  depth: 9999
  quiet: true
addons:
  sonarcloud:
    organization: "dadoonet-github"
#before_install:
#  - sudo apt-get -qq update
#  - sudo apt-get install -y tesseract-ocr
before_script:
  - sudo sysctl -w vm.max_map_count=262144
script:
  - mvn --batch-mode clean verify
  - mvn --batch-mode clean verify -Psecurity
after_success:
  - ./travis.sh
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
branches:
  only:
    - "master"
