language: java
sudo: true
jdk:
  - oraclejdk8
install: true
services:
  - docker
addons:
  sonarcloud:
    organization: "dadoonet-github"
#before_install:
#  - sudo apt-get -qq update
#  - sudo apt-get install -y tesseract-ocr
before_script:
  - sudo sysctl -w vm.max_map_count=262144
script:
  - mvn --batch-mode clean verify -Pes-5x
  - mvn --batch-mode clean verify -Poss
  - mvn --batch-mode clean verify
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
after_success:
  - "[[ ${TRAVIS_PULL_REQUEST} == 'false' ]] && [[ ${TRAVIS_TAG} == '' ]] && mvn deploy -DskipTests --settings deploy-settings.xml"
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
